import { PERMISSIONS, type PermissionCode } from './permissions';
import type { RoleCode } from './roles';

const ADMIN_PERMISSIONS: readonly PermissionCode[] = [
  PERMISSIONS.USERS_MANAGE,
  PERMISSIONS.ROLES_MANAGE,
  PERMISSIONS.INVENTORY_READ,
  PERMISSIONS.INVENTORY_WRITE,
  PERMISSIONS.EVENTS_READ,
  PERMISSIONS.EVENTS_WRITE,
  PERMISSIONS.BOXES_READ,
  PERMISSIONS.BOXES_WRITE,
  PERMISSIONS.EXPORTS_READ
];

const WAREHOUSE_STAFF_PERMISSIONS: readonly PermissionCode[] = [
  PERMISSIONS.INVENTORY_READ,
  PERMISSIONS.INVENTORY_WRITE,
  PERMISSIONS.EVENTS_READ,
  PERMISSIONS.EVENTS_WRITE,
  PERMISSIONS.BOXES_READ,
  PERMISSIONS.BOXES_WRITE,
  PERMISSIONS.EXPORTS_READ
];

const OFFICE_STAFF_PERMISSIONS: readonly PermissionCode[] = [
  PERMISSIONS.INVENTORY_READ,
  PERMISSIONS.EVENTS_READ,
  PERMISSIONS.EVENTS_WRITE,
  PERMISSIONS.BOXES_READ,
  PERMISSIONS.EXPORTS_READ
];

const GUEST_PERMISSIONS: readonly PermissionCode[] = [
  PERMISSIONS.INVENTORY_READ,
  PERMISSIONS.EVENTS_READ,
  PERMISSIONS.BOXES_READ
];

export const ROLE_PERMISSION_MATRIX: Record<RoleCode, readonly PermissionCode[]> = {
  ADMIN: ADMIN_PERMISSIONS,
  WAREHOUSE_STAFF: WAREHOUSE_STAFF_PERMISSIONS,
  OFFICE_STAFF: OFFICE_STAFF_PERMISSIONS,
  GUEST: GUEST_PERMISSIONS
};

export function getPermissionsForRole(role: RoleCode): readonly PermissionCode[] {
  return ROLE_PERMISSION_MATRIX[role];
}

export function hasRolePermission(role: RoleCode, permission: PermissionCode): boolean {
  return ROLE_PERMISSION_MATRIX[role].includes(permission);
}
